#version: '3'
#services:
#   carteira:
#      build:
#         dockerfile: ./dockerfile/DockerFile
#         context: .
#      image: gustavosc/carteira
#      restart: unless-stopped
#      container_name: carteira
#      ports:
#         - 8081:8081
#      networks: 
#         - wallet
#      depends_on: 
#      - db      
#   db:
#      image: mysql:5.6
#      restart: unless-stopped
#      environment:
#         MYSQL_ROOT_HOST: '%'
#         MYSQL_DATABASE: carteira
#         MYSQL_USER: root
#         MYSQL__PASSWORD: password
#      ports:
#         - '3306:3306'
#      volumes:
#         - ./docker/volume_mysql:/var/lib/mysql
#      networks: 
#         - wallet 
#         
#volumes:
#  my-db:      
#networks:
#   wallet:
#    driver: bridge
#    
#      